CREATE DATABASE IF NOT EXISTS ResenasWeb;

CREATE TABLE IF NOT EXISTS ResenasWeb.resenas (
  id_resena INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL,
  idVehiculo INT NOT NULL,
  comentario VARCHAR(255),
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id_resena)
);

CREATE USER IF NOT EXISTS 'josephsito'@'%' IDENTIFIED BY '123456789';
GRANT ALL PRIVILEGES ON ResenasWeb.* TO 'josephsito'@'%';
FLUSH PRIVILEGES;

